# Generated by Django 3.2.5 on 2021-08-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password2',
            new_name='password_confirmation',
        ),
    ]
